

Data distribution to clients: 100%|█████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:06<00:00,  1.79it/s]
Global Rounds:   0%|                                                                                                              | 0/5 [00:00<?, ?it/s]
running clients:   0%|                                                                                                           | 0/11 [00:00<?, ?it/s]
data available [0.08275862068965517, 0.041379310344827586, 0.12413793103448276, 0.1310344827586207, 0.027586206896551724, 0.0896551724137931, 0.1103448275862069, 0.1310344827586207, 0.07586206896551724, 0.13793103448275862, 0.04827586206896552]
Finished creating FedAvg server.
Exp no0 : users selected for global iteration 0 are : [71, 7, 189, 202, 208, 0, 160, 10, 105, 68, 139]
Global Rounds:   0%|                                                                                                              | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/proj/sourasb-220503/Fed-DIPA2/main.py", line 51, in <module>
    main(args)
  File "/proj/sourasb-220503/Fed-DIPA2/main.py", line 34, in main
    server.train()
  File "/proj/sourasb-220503/Fed-DIPA2/src/Fedavg/FedAvgServer.py", line 230, in train
    user.train()  # * user.train_samples
    ^^^^^^^^^^^^
  File "/proj/sourasb-220503/Fed-DIPA2/src/Fedavg/UserFedAvg.py", line 384, in train
    self.wandb.log({ "step" : iter*batch + iter,  "%02d_loss" % (self.id) : loss})
                              ~~~~~~~~~~~^~~~~~
TypeError: can only concatenate list (not "int") to list